# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FrostyX's blog
email: frostyx@email.cz
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Jakub Kadlčík (aka FrostyX)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frostyx.cz" # the base hostname & protocol for your site
twitter_username: frostyx
github_username:  frostyx
permalink: /posts/:title

# Build settings
markdown: kramdown

kramdown:
  # Auto-generate ID's for headings
  # https://milanaryal.com/adding-hover-anchor-links-to-header-on-github-pages-using-jekyll/
  auto_ids: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
